### ISSUE TITLE
Reference Spectra Example Issue in Documentation

### ISSUE THREAD

**Issue by tkeller12** [DNPLab/DNPLab#522]
Unexpected failing examples:

    ../../examples/02_Analysis/plot_04_reference_spectra.py failed leaving traceback:

    Traceback (most recent call last):
      File "/github/workspace/examples/02_Analysis/plot_04_reference_spectra.py", line 22, in <module>
        data = dnp.load(file_name_path)
      File "/github/workspace/dnplab/io/load.py", line 59, in load
        return load_file(
      File "/github/workspace/dnplab/io/load.py", line 114, in load_file
        data = h5.load_h5(path, *args, **kwargs)
      File "/github/workspace/dnplab/io/h5.py", line 23, in load_h5
        f = h5py.File(path, "r")
      File "/usr/local/lib/python3.8/site-packages/h5py/_hl/files.py", line 562, in __init__
        fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
      File "/usr/local/lib/python3.8/site-packages/h5py/_hl/files.py", line 235, in make_fid
        fid = h5f.open(name, flags, fapl=fapl)
      File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
      File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
      File "h5py/h5f.pyx", line 102, in h5py.h5f.open
    FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '../../data/h5/PowerBuildUpAligned.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

-------------------------------------------------------------------------------
make: *** [Makefile:24: html] Error 2
[sphinx-action] Starting sphinx-action build.
Running: pip install sphinx-gallery==0.15 && pip install sphinx_rtd_theme==2.0.0 && pip install matplotlib==3.7 && pip install numpy==1.24 && pip install scipy==1.10.0 && pip install h5py==3.10.0 && pip install scikit-rf==0.30.0 && h5py==3.10.0
Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
  File "/sphinx_action/action.py", line 167, in build_all_docs
    raise RuntimeError("Build failed")
RuntimeError: Build failed
====================================
Building docs in docs/
====================================
[sphinx-action] Running: ['make', 'html', '-e']
[sphinx-action] Build failed with 0 warnings

**Comment by tkeller12** [comment]
For complete log see:
https://github.com/DNPLab/DNPLab/actions/runs/10012445182/job/27677985441?pr=521

**Comment by tkeller12** [comment]
Change the example to load a single toluene spectrum and reference it.
