### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.sip'

### ISSUE THREAD

**Issue by ylin00** [DNPLab/DNPLab#64]
```python
>>> import dnplab as dnp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tmaly/Documents/Repositories/ODNP/DNPLab/dnplab/__init__.py", line 8, in <module>
    from . import hydrationGUI
  File "/Users/tmaly/Documents/Repositories/ODNP/DNPLab/dnplab/hydrationGUI.py", line 10, in <module>
    from PyQt5 import QtWidgets, QtGui, QtCore
ModuleNotFoundError: No module named 'PyQt5.sip'
PqQt5 is still version 5.14. I already uninstalled it and let DNPLab re-install it (so I get a version that is compatible). But no luck yet.
```

**Comment by thorstenmaly** [comment]
We will remove the requirement to install PyQt5 in the next release. This is only used for the hydration module, currently only used by users in the Han lab. We should revisit this, if more GUIs are developed.
